### ISSUE TITLE
Question about development

### ISSUE THREAD

**Issue by DavidMorgan92** [a-chris/react-express-workspaces-heroku#1]
Hi, thanks for this, it works perfectly for deploying to Heroku.

I have a question about how I can develop using this method. For development I've added this watch script:
`"watch": "concurrently \"yarn workspace server watch\" \"yarn workspace client start\""`

And the watch script in the server:
`"watch": "tsc && nodemon dist/index.js"`

Since in deployment the server is serving the React app the API requests come from the same origin. In development, this means that to use the React dev server I have to put the Express server on a different port, so I have to use cross-origin requests. I can set this up but it's not necessary for the deployed version so it seems like it's not quite right.

I hope I'm phrasing this well enough. Basically I'm wondering how you set up this environment for development, so that you get the React app and the server automatically reloading when you change the code.

Thank you.

**Comment by DavidMorgan92** [comment]
I found a solution by configuring the proxy setting in the client's package.json. This makes webpack direct fetch requests to the server running on a different port for development but is ignored when deployed.

**Comment by a-chris** [comment]
@DavidMorgan92 interesting, thanks for reporting the solution 🙏
